rbns_data = {
	"RBM47" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF654ZXW/@@download/ENCFF654ZXW.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF546CET/@@download/ENCFF546CET.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF650UUT/@@download/ENCFF650UUT.fastq.gz",
		"60nM" : "https://www.encodeproject.org/files/ENCFF152YBN/@@download/ENCFF152YBN.fastq.gz",
		"240nM" : "https://www.encodeproject.org/files/ENCFF051CMM/@@download/ENCFF051CMM.fastq.gz",
		"960nM" : "https://www.encodeproject.org/files/ENCFF753GNQ/@@download/ENCFF753GNQ.fastq.gz",
		"3800nM" : "https://www.encodeproject.org/files/ENCFF211NKK/@@download/ENCFF211NKK.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF148TFJ/@@download/ENCFF148TFJ.fastq.gz" },
	"FUBP3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF130HUZ/@@download/ENCFF130HUZ.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF012DBP/@@download/ENCFF012DBP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF146YJF/@@download/ENCFF146YJF.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF071WGX/@@download/ENCFF071WGX.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF626IFM/@@download/ENCFF626IFM.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF668WQD/@@download/ENCFF668WQD.fastq.gz" },
	"RBM6" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF002VNX/@@download/ENCFF002VNX.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF133WMF/@@download/ENCFF133WMF.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF229GWE/@@download/ENCFF229GWE.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF880ULO/@@download/ENCFF880ULO.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF796ZYM/@@download/ENCFF796ZYM.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF771ECU/@@download/ENCFF771ECU.fastq.gz" },
	"RBM25" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF066NPP/@@download/ENCFF066NPP.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF897ZRK/@@download/ENCFF897ZRK.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF701SYD/@@download/ENCFF701SYD.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF410QTN/@@download/ENCFF410QTN.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF353VKL/@@download/ENCFF353VKL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF248GRF/@@download/ENCFF248GRF.fastq.gz" },
	"FUS" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF441MLG/@@download/ENCFF441MLG.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF448YEM/@@download/ENCFF448YEM.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF375AIG/@@download/ENCFF375AIG.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF680AGJ/@@download/ENCFF680AGJ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF739HXK/@@download/ENCFF739HXK.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF692LOC/@@download/ENCFF692LOC.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF871MJA/@@download/ENCFF871MJA.fastq.gz" },
	"CELF1" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF002DFK/@@download/ENCFF002DFK.fastq.gz",
		"4nM" : "https://www.encodeproject.org/files/ENCFF002DFP/@@download/ENCFF002DFP.fastq.gz",
		"16nM" : "https://www.encodeproject.org/files/ENCFF002DFN/@@download/ENCFF002DFN.fastq.gz",
		"64nM" : "https://www.encodeproject.org/files/ENCFF002DFR/@@download/ENCFF002DFR.fastq.gz",
		"130nM" : "https://www.encodeproject.org/files/ENCFF002DFM/@@download/ENCFF002DFM.fastq.gz",
		"500nM" : "https://www.encodeproject.org/files/ENCFF002DFQ/@@download/ENCFF002DFQ.fastq.gz",
		"1000nM" : "https://www.encodeproject.org/files/ENCFF002DFL/@@download/ENCFF002DFL.fastq.gz",
		"2000nM" : "https://www.encodeproject.org/files/ENCFF002DFO/@@download/ENCFF002DFO.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF002DFS/@@download/ENCFF002DFS.fastq.gz" },
	"MSI1" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF928YLI/@@download/ENCFF928YLI.fastq.gz",
		"500pM" : "https://www.encodeproject.org/files/ENCFF518PVS/@@download/ENCFF518PVS.fastq.gz",
		"2nM" : "https://www.encodeproject.org/files/ENCFF200FEI/@@download/ENCFF200FEI.fastq.gz",
		"8nM" : "https://www.encodeproject.org/files/ENCFF278ERO/@@download/ENCFF278ERO.fastq.gz",
		"16nM" : "https://www.encodeproject.org/files/ENCFF922BHB/@@download/ENCFF922BHB.fastq.gz",
		"64nM" : "https://www.encodeproject.org/files/ENCFF695CIJ/@@download/ENCFF695CIJ.fastq.gz",
		"256nM" : "https://www.encodeproject.org/files/ENCFF049COJ/@@download/ENCFF049COJ.fastq.gz",
		"1000nM" : "https://www.encodeproject.org/files/ENCFF110LAR/@@download/ENCFF110LAR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF919AUN/@@download/ENCFF919AUN.fastq.gz" },
	"CNOT4" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF763IRH/@@download/ENCFF763IRH.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF798CEK/@@download/ENCFF798CEK.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF962UIH/@@download/ENCFF962UIH.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF751TQU/@@download/ENCFF751TQU.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF897BPT/@@download/ENCFF897BPT.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF421KWK/@@download/ENCFF421KWK.fastq.gz" },
	"RBM23" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF621AFM/@@download/ENCFF621AFM.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF601SFI/@@download/ENCFF601SFI.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF776JOW/@@download/ENCFF776JOW.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF237EFE/@@download/ENCFF237EFE.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF249THA/@@download/ENCFF249THA.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF462XAL/@@download/ENCFF462XAL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF314LQZ/@@download/ENCFF314LQZ.fastq.gz" },
	"SRSF2" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF889JSB/@@download/ENCFF889JSB.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF443RLZ/@@download/ENCFF443RLZ.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF203RCX/@@download/ENCFF203RCX.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF427KXG/@@download/ENCFF427KXG.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF044HZO/@@download/ENCFF044HZO.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF395BSA/@@download/ENCFF395BSA.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF087BBT/@@download/ENCFF087BBT.fastq.gz" },
	"RBM4" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF401FZE/@@download/ENCFF401FZE.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF290VRZ/@@download/ENCFF290VRZ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF662YDT/@@download/ENCFF662YDT.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF940CRO/@@download/ENCFF940CRO.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF527ZSP/@@download/ENCFF527ZSP.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF864DRM/@@download/ENCFF864DRM.fastq.gz" },
	"A1CF" : {
		"1300nM" : "https://www.encodeproject.org/files/ENCFF305UGG/@@download/ENCFF305UGG.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF884QIH/@@download/ENCFF884QIH.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF187MDO/@@download/ENCFF187MDO.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF274IJN/@@download/ENCFF274IJN.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF194FOG/@@download/ENCFF194FOG.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF689ELM/@@download/ENCFF689ELM.fastq.gz" },
	"ZNF326" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF743RCD/@@download/ENCFF743RCD.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF730GYB/@@download/ENCFF730GYB.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF398TUH/@@download/ENCFF398TUH.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF325OGD/@@download/ENCFF325OGD.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF679WSU/@@download/ENCFF679WSU.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF505ATJ/@@download/ENCFF505ATJ.fastq.gz" },
	"PCBP2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF798SMM/@@download/ENCFF798SMM.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF058WPN/@@download/ENCFF058WPN.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF691SCA/@@download/ENCFF691SCA.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF053JNP/@@download/ENCFF053JNP.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF020KTF/@@download/ENCFF020KTF.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF816DFV/@@download/ENCFF816DFV.fastq.gz" },
	"IGF2BP2" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF032AUY/@@download/ENCFF032AUY.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF074RIC/@@download/ENCFF074RIC.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF998ZLV/@@download/ENCFF998ZLV.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF758QOA/@@download/ENCFF758QOA.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF833VXY/@@download/ENCFF833VXY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF331ENP/@@download/ENCFF331ENP.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF917XEN/@@download/ENCFF917XEN.fastq.gz" },
	"TIA1" : {
		"320nM" : "https://www.encodeproject.org/files/ENCFF897ONM/@@download/ENCFF897ONM.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF815CIK/@@download/ENCFF815CIK.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF400JXE/@@download/ENCFF400JXE.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF278GIB/@@download/ENCFF278GIB.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF374UTI/@@download/ENCFF374UTI.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF295WRQ/@@download/ENCFF295WRQ.fastq.gz" },
	"SRSF11" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF877DUW/@@download/ENCFF877DUW.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF205NWX/@@download/ENCFF205NWX.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF040OXG/@@download/ENCFF040OXG.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF828WZL/@@download/ENCFF828WZL.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF795EEX/@@download/ENCFF795EEX.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF248EWX/@@download/ENCFF248EWX.fastq.gz" },
	"ZCRB1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF758ORV/@@download/ENCFF758ORV.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF526DSN/@@download/ENCFF526DSN.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF449IAQ/@@download/ENCFF449IAQ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF862JMB/@@download/ENCFF862JMB.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF678GKT/@@download/ENCFF678GKT.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF421KWK/@@download/ENCFF421KWK.fastq.gz" },
	"RBMS2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF324ZYT/@@download/ENCFF324ZYT.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF820PEE/@@download/ENCFF820PEE.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF231KTD/@@download/ENCFF231KTD.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF273JFY/@@download/ENCFF273JFY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF452FCJ/@@download/ENCFF452FCJ.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF395NJM/@@download/ENCFF395NJM.fastq.gz" },
	"RC3H1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF189FRP/@@download/ENCFF189FRP.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF540SRD/@@download/ENCFF540SRD.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF393MNZ/@@download/ENCFF393MNZ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF732QEB/@@download/ENCFF732QEB.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF607ZLL/@@download/ENCFF607ZLL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF016HYN/@@download/ENCFF016HYN.fastq.gz" },
	"HNRNPH2" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF242LBP/@@download/ENCFF242LBP.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF183XXP/@@download/ENCFF183XXP.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF471ZPP/@@download/ENCFF471ZPP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF341AET/@@download/ENCFF341AET.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF789QRU/@@download/ENCFF789QRU.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF271YCR/@@download/ENCFF271YCR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF753YND/@@download/ENCFF753YND.fastq.gz" },
	"EWSR1" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF160WCN/@@download/ENCFF160WCN.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF806UZR/@@download/ENCFF806UZR.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF690OPZ/@@download/ENCFF690OPZ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF561OTA/@@download/ENCFF561OTA.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF846YUO/@@download/ENCFF846YUO.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF352GUJ/@@download/ENCFF352GUJ.fastq.gz" },
	"HNRNPL" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF086FCD/@@download/ENCFF086FCD.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF004ECZ/@@download/ENCFF004ECZ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF066AFW/@@download/ENCFF066AFW.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF407TKA/@@download/ENCFF407TKA.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF929YDP/@@download/ENCFF929YDP.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF395BBW/@@download/ENCFF395BBW.fastq.gz" },
	"PCBP1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF134JFO/@@download/ENCFF134JFO.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF015VYZ/@@download/ENCFF015VYZ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF965AGF/@@download/ENCFF965AGF.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF975PLP/@@download/ENCFF975PLP.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF111WYI/@@download/ENCFF111WYI.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF395ETZ/@@download/ENCFF395ETZ.fastq.gz" },
	"ESRP1" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF517JVP/@@download/ENCFF517JVP.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF201IIS/@@download/ENCFF201IIS.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF497OVV/@@download/ENCFF497OVV.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF866SSJ/@@download/ENCFF866SSJ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF709NVS/@@download/ENCFF709NVS.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF249MKN/@@download/ENCFF249MKN.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF353BLN/@@download/ENCFF353BLN.fastq.gz" },
	"SF1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF310EFE/@@download/ENCFF310EFE.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF894RNB/@@download/ENCFF894RNB.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF620JEI/@@download/ENCFF620JEI.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF574ATK/@@download/ENCFF574ATK.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF550BZS/@@download/ENCFF550BZS.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF395BBW/@@download/ENCFF395BBW.fastq.gz" },
	"FUBP1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF884IBI/@@download/ENCFF884IBI.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF624STJ/@@download/ENCFF624STJ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF677VDN/@@download/ENCFF677VDN.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF597MHG/@@download/ENCFF597MHG.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF319TXL/@@download/ENCFF319TXL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF586EOO/@@download/ENCFF586EOO.fastq.gz" },
	"HNRNPK" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF261ZHZ/@@download/ENCFF261ZHZ.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF732XFP/@@download/ENCFF732XFP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF281CNE/@@download/ENCFF281CNE.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF004OKN/@@download/ENCFF004OKN.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF674RCB/@@download/ENCFF674RCB.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF537ORU/@@download/ENCFF537ORU.fastq.gz" },
	"KHDRBS3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF612DYP/@@download/ENCFF612DYP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF993IHW/@@download/ENCFF993IHW.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF118MEC/@@download/ENCFF118MEC.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF793XRU/@@download/ENCFF793XRU.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF385FEF/@@download/ENCFF385FEF.fastq.gz" },
	"TRA2A" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF499TRO/@@download/ENCFF499TRO.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF209PWZ/@@download/ENCFF209PWZ.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF674LSW/@@download/ENCFF674LSW.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF369HLN/@@download/ENCFF369HLN.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF053JOA/@@download/ENCFF053JOA.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF406VDD/@@download/ENCFF406VDD.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF979UHU/@@download/ENCFF979UHU.fastq.gz" },
	"TAF15" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF160CZF/@@download/ENCFF160CZF.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF032XJW/@@download/ENCFF032XJW.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF206DZS/@@download/ENCFF206DZS.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF686CWM/@@download/ENCFF686CWM.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF662TOD/@@download/ENCFF662TOD.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF304HMY/@@download/ENCFF304HMY.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF325RIN/@@download/ENCFF325RIN.fastq.gz" },
	"IGF2BP1" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF002DGH/@@download/ENCFF002DGH.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF002DGL/@@download/ENCFF002DGL.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF002DGJ/@@download/ENCFF002DGJ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF002DGM/@@download/ENCFF002DGM.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF002DGK/@@download/ENCFF002DGK.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF002DGI/@@download/ENCFF002DGI.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF002DGN/@@download/ENCFF002DGN.fastq.gz" },
	"TARDBP" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF023PUC/@@download/ENCFF023PUC.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF147IXH/@@download/ENCFF147IXH.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF864BPI/@@download/ENCFF864BPI.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF552GCD/@@download/ENCFF552GCD.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF044GED/@@download/ENCFF044GED.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF483NLQ/@@download/ENCFF483NLQ.fastq.gz" },
	"SFPQ" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF092VIT/@@download/ENCFF092VIT.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF980WQW/@@download/ENCFF980WQW.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF852PPY/@@download/ENCFF852PPY.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF642XCH/@@download/ENCFF642XCH.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF597YAL/@@download/ENCFF597YAL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF816DFV/@@download/ENCFF816DFV.fastq.gz" },
	"ILF2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF647LEW/@@download/ENCFF647LEW.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF003OLV/@@download/ENCFF003OLV.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF383QAM/@@download/ENCFF383QAM.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF096YGY/@@download/ENCFF096YGY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF539DBG/@@download/ENCFF539DBG.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF248GRF/@@download/ENCFF248GRF.fastq.gz" },
	"RBM22" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF518QQN/@@download/ENCFF518QQN.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF745RRQ/@@download/ENCFF745RRQ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF870LSB/@@download/ENCFF870LSB.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF576DJF/@@download/ENCFF576DJF.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF222JFA/@@download/ENCFF222JFA.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF767MZQ/@@download/ENCFF767MZQ.fastq.gz" },
	"PTBP3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF002BYO/@@download/ENCFF002BYO.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF002BYK/@@download/ENCFF002BYK.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF002BYP/@@download/ENCFF002BYP.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF002BYL/@@download/ENCFF002BYL.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF002BYJ/@@download/ENCFF002BYJ.fastq.gz",
		"3900nM" : "https://www.encodeproject.org/files/ENCFF002BYM/@@download/ENCFF002BYM.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF002BYQ/@@download/ENCFF002BYQ.fastq.gz" },
	"PUF60" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF147YOV/@@download/ENCFF147YOV.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF092OVI/@@download/ENCFF092OVI.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF262OPY/@@download/ENCFF262OPY.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF748VRH/@@download/ENCFF748VRH.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF071TXE/@@download/ENCFF071TXE.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF838ARR/@@download/ENCFF838ARR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF871MJA/@@download/ENCFF871MJA.fastq.gz" },
	"ELAVL4" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF144IPW/@@download/ENCFF144IPW.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF177IIK/@@download/ENCFF177IIK.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF947KRL/@@download/ENCFF947KRL.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF729VNY/@@download/ENCFF729VNY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF639TKW/@@download/ENCFF639TKW.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF418KRY/@@download/ENCFF418KRY.fastq.gz" },
	"KHSRP" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF385FOT/@@download/ENCFF385FOT.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF778ABV/@@download/ENCFF778ABV.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF487JGC/@@download/ENCFF487JGC.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF608BCN/@@download/ENCFF608BCN.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF641RTT/@@download/ENCFF641RTT.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF670GMS/@@download/ENCFF670GMS.fastq.gz" },
	"SRSF9" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF927STX/@@download/ENCFF927STX.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF413ETY/@@download/ENCFF413ETY.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF779KVV/@@download/ENCFF779KVV.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF305KBH/@@download/ENCFF305KBH.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF042JZR/@@download/ENCFF042JZR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF483NLQ/@@download/ENCFF483NLQ.fastq.gz" },
	"RBM45" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF303TMB/@@download/ENCFF303TMB.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF902WXY/@@download/ENCFF902WXY.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF575BTH/@@download/ENCFF575BTH.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF660MFW/@@download/ENCFF660MFW.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF294KSP/@@download/ENCFF294KSP.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF309HWO/@@download/ENCFF309HWO.fastq.gz" },
	"RBFOX3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF719LOX/@@download/ENCFF719LOX.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF629DZC/@@download/ENCFF629DZC.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF963SOG/@@download/ENCFF963SOG.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF942RUM/@@download/ENCFF942RUM.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF405QFZ/@@download/ENCFF405QFZ.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF771NKG/@@download/ENCFF771NKG.fastq.gz" },
	"EIF4G2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF747XEL/@@download/ENCFF747XEL.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF483PKV/@@download/ENCFF483PKV.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF613BOZ/@@download/ENCFF613BOZ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF798BTI/@@download/ENCFF798BTI.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF531KCO/@@download/ENCFF531KCO.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF668QER/@@download/ENCFF668QER.fastq.gz" },
	"HNRNPA0" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF373FBO/@@download/ENCFF373FBO.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF156FZK/@@download/ENCFF156FZK.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF114JMF/@@download/ENCFF114JMF.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF210HCF/@@download/ENCFF210HCF.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF836VGG/@@download/ENCFF836VGG.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF668WQD/@@download/ENCFF668WQD.fastq.gz" },
	"RBM24" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF355UIV/@@download/ENCFF355UIV.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF211URD/@@download/ENCFF211URD.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF948RIV/@@download/ENCFF948RIV.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF583TUC/@@download/ENCFF583TUC.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF698TXB/@@download/ENCFF698TXB.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF771ECU/@@download/ENCFF771ECU.fastq.gz" },
	"SRSF5" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF200YPB/@@download/ENCFF200YPB.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF901VZV/@@download/ENCFF901VZV.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF229OOD/@@download/ENCFF229OOD.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF130TEX/@@download/ENCFF130TEX.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF804SHE/@@download/ENCFF804SHE.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF388IAE/@@download/ENCFF388IAE.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF325RIN/@@download/ENCFF325RIN.fastq.gz" },
	"RBM15B" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF461ZWO/@@download/ENCFF461ZWO.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF772AJT/@@download/ENCFF772AJT.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF037HIV/@@download/ENCFF037HIV.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF234HVI/@@download/ENCFF234HVI.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF160QZD/@@download/ENCFF160QZD.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF969DHV/@@download/ENCFF969DHV.fastq.gz" },
	"ZFP36" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF006ZXM/@@download/ENCFF006ZXM.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF113XPZ/@@download/ENCFF113XPZ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF149ZPE/@@download/ENCFF149ZPE.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF089AAP/@@download/ENCFF089AAP.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF248KPL/@@download/ENCFF248KPL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF689ELM/@@download/ENCFF689ELM.fastq.gz" },
	"RBM41" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF143JJC/@@download/ENCFF143JJC.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF658PGT/@@download/ENCFF658PGT.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF590PBM/@@download/ENCFF590PBM.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF550YXW/@@download/ENCFF550YXW.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF644BBX/@@download/ENCFF644BBX.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF309HWO/@@download/ENCFF309HWO.fastq.gz" },
	"NOVA1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF557ODA/@@download/ENCFF557ODA.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF773ACP/@@download/ENCFF773ACP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF850IFW/@@download/ENCFF850IFW.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF892LGW/@@download/ENCFF892LGW.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF510DKF/@@download/ENCFF510DKF.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF357LTA/@@download/ENCFF357LTA.fastq.gz" },
	"PABPN1L" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF988CZO/@@download/ENCFF988CZO.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF219HWQ/@@download/ENCFF219HWQ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF883BVH/@@download/ENCFF883BVH.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF992FMO/@@download/ENCFF992FMO.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF419ZIO/@@download/ENCFF419ZIO.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF670GMS/@@download/ENCFF670GMS.fastq.gz" },
	"PRR3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF002RAY/@@download/ENCFF002RAY.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF859IFZ/@@download/ENCFF859IFZ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF584IYE/@@download/ENCFF584IYE.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF305FZN/@@download/ENCFF305FZN.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF016DMQ/@@download/ENCFF016DMQ.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF137VIC/@@download/ENCFF137VIC.fastq.gz" },
	"SNRPA" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF279HZP/@@download/ENCFF279HZP.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF169FUR/@@download/ENCFF169FUR.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF729AXE/@@download/ENCFF729AXE.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF818QHZ/@@download/ENCFF818QHZ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF658HXU/@@download/ENCFF658HXU.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF385FEF/@@download/ENCFF385FEF.fastq.gz" },
	"DAZAP1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF548LGA/@@download/ENCFF548LGA.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF159FNQ/@@download/ENCFF159FNQ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF766DOA/@@download/ENCFF766DOA.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF887GOK/@@download/ENCFF887GOK.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF387GNF/@@download/ENCFF387GNF.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF425XLJ/@@download/ENCFF425XLJ.fastq.gz" },
	"KHDRBS2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF803LHT/@@download/ENCFF803LHT.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF725OYS/@@download/ENCFF725OYS.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF276YSZ/@@download/ENCFF276YSZ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF234WAZ/@@download/ENCFF234WAZ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF903TJA/@@download/ENCFF903TJA.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF449THM/@@download/ENCFF449THM.fastq.gz" },
	"SRSF8" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF975GRN/@@download/ENCFF975GRN.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF746BQQ/@@download/ENCFF746BQQ.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF172SZM/@@download/ENCFF172SZM.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF260OIA/@@download/ENCFF260OIA.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF625PWF/@@download/ENCFF625PWF.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF046HXG/@@download/ENCFF046HXG.fastq.gz" },
	"HNRNPA2B1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF633PYG/@@download/ENCFF633PYG.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF272CDH/@@download/ENCFF272CDH.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF871IQB/@@download/ENCFF871IQB.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF284NLC/@@download/ENCFF284NLC.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF486QQA/@@download/ENCFF486QQA.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF284GGX/@@download/ENCFF284GGX.fastq.gz" },
	"PUM1" : {
		"320nM" : "https://www.encodeproject.org/files/ENCFF266PHU/@@download/ENCFF266PHU.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF894MLG/@@download/ENCFF894MLG.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF090QVU/@@download/ENCFF090QVU.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF574TBN/@@download/ENCFF574TBN.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF345UJY/@@download/ENCFF345UJY.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF761JAF/@@download/ENCFF761JAF.fastq.gz" },
	"SRSF10" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF208GAK/@@download/ENCFF208GAK.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF272IIN/@@download/ENCFF272IIN.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF593KNI/@@download/ENCFF593KNI.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF386EWB/@@download/ENCFF386EWB.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF908JKG/@@download/ENCFF908JKG.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF457XQS/@@download/ENCFF457XQS.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF532AHD/@@download/ENCFF532AHD.fastq.gz" },
	"UNK" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF035LLB/@@download/ENCFF035LLB.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF874MPY/@@download/ENCFF874MPY.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF256CNE/@@download/ENCFF256CNE.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF474ABY/@@download/ENCFF474ABY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF084FZV/@@download/ENCFF084FZV.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF385XEF/@@download/ENCFF385XEF.fastq.gz" },
	"RBM4B" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF642LIU/@@download/ENCFF642LIU.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF933GYK/@@download/ENCFF933GYK.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF414MZG/@@download/ENCFF414MZG.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF030UYE/@@download/ENCFF030UYE.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF224QDZ/@@download/ENCFF224QDZ.fastq.gz" },
	"RBMS3" : {
		"20nM" : "https://www.encodeproject.org/files/ENCFF270MEX/@@download/ENCFF270MEX.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF815HRK/@@download/ENCFF815HRK.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF296APU/@@download/ENCFF296APU.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF159XZR/@@download/ENCFF159XZR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF224QDZ/@@download/ENCFF224QDZ.fastq.gz" },
	"TRNAU1AP" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF823RGZ/@@download/ENCFF823RGZ.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF369WZD/@@download/ENCFF369WZD.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF228IGY/@@download/ENCFF228IGY.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF330UOX/@@download/ENCFF330UOX.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF339GLP/@@download/ENCFF339GLP.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF395ETZ/@@download/ENCFF395ETZ.fastq.gz" },
	"CPEB1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF960JKZ/@@download/ENCFF960JKZ.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF859RIY/@@download/ENCFF859RIY.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF903JOE/@@download/ENCFF903JOE.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF808XIS/@@download/ENCFF808XIS.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF013YVD/@@download/ENCFF013YVD.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF214QKC/@@download/ENCFF214QKC.fastq.gz" },
	"BOLL" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF025KXN/@@download/ENCFF025KXN.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF471GJF/@@download/ENCFF471GJF.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF305QDN/@@download/ENCFF305QDN.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF954BBZ/@@download/ENCFF954BBZ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF939KQG/@@download/ENCFF939KQG.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF812GKQ/@@download/ENCFF812GKQ.fastq.gz" },
	"NUPL2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF452SPV/@@download/ENCFF452SPV.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF558MQD/@@download/ENCFF558MQD.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF174KHL/@@download/ENCFF174KHL.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF967YLZ/@@download/ENCFF967YLZ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF143HKO/@@download/ENCFF143HKO.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF137VIC/@@download/ENCFF137VIC.fastq.gz" },
	"PCBP4" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF922HKT/@@download/ENCFF922HKT.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF024KDW/@@download/ENCFF024KDW.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF871CCW/@@download/ENCFF871CCW.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF065MZA/@@download/ENCFF065MZA.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF814SIC/@@download/ENCFF814SIC.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF519RUA/@@download/ENCFF519RUA.fastq.gz" },
	"RALYL" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF432AZE/@@download/ENCFF432AZE.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF345AMU/@@download/ENCFF345AMU.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF464RSK/@@download/ENCFF464RSK.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF532TOJ/@@download/ENCFF532TOJ.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF864DRM/@@download/ENCFF864DRM.fastq.gz" },
	"HNRNPDL" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF694BLE/@@download/ENCFF694BLE.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF495RWY/@@download/ENCFF495RWY.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF613XWY/@@download/ENCFF613XWY.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF566PVD/@@download/ENCFF566PVD.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF032BNE/@@download/ENCFF032BNE.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF969DHV/@@download/ENCFF969DHV.fastq.gz" },
	"DAZ3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF921PCX/@@download/ENCFF921PCX.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF463SEP/@@download/ENCFF463SEP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF633VVB/@@download/ENCFF633VVB.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF182ZXE/@@download/ENCFF182ZXE.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF756JHY/@@download/ENCFF756JHY.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF541WDR/@@download/ENCFF541WDR.fastq.gz" },
	"HNRNPCL1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF316GAF/@@download/ENCFF316GAF.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF729PSS/@@download/ENCFF729PSS.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF150PUV/@@download/ENCFF150PUV.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF963SCO/@@download/ENCFF963SCO.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF442IBY/@@download/ENCFF442IBY.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF541WDR/@@download/ENCFF541WDR.fastq.gz" },
	"SRSF4" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF637PAB/@@download/ENCFF637PAB.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF695JWD/@@download/ENCFF695JWD.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF707DGD/@@download/ENCFF707DGD.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF801NRU/@@download/ENCFF801NRU.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF424VHK/@@download/ENCFF424VHK.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF659GOB/@@download/ENCFF659GOB.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF472NVZ/@@download/ENCFF472NVZ.fastq.gz" },
	"HNRNPC" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF866DQR/@@download/ENCFF866DQR.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF083JEO/@@download/ENCFF083JEO.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF366SWO/@@download/ENCFF366SWO.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF304NRR/@@download/ENCFF304NRR.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF235WCJ/@@download/ENCFF235WCJ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF161YRQ/@@download/ENCFF161YRQ.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF658BYB/@@download/ENCFF658BYB.fastq.gz" },
	"HNRNPD" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF002DFT/@@download/ENCFF002DFT.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF002DFX/@@download/ENCFF002DFX.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF002DFV/@@download/ENCFF002DFV.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF002DFY/@@download/ENCFF002DFY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF002DFU/@@download/ENCFF002DFU.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF002DFW/@@download/ENCFF002DFW.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF002DFZ/@@download/ENCFF002DFZ.fastq.gz" },
	"HNRNPF" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF002DGA/@@download/ENCFF002DGA.fastq.gz",
		"5nM" : "https://www.encodeproject.org/files/ENCFF002DGE/@@download/ENCFF002DGE.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF002DGC/@@download/ENCFF002DGC.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF002DGF/@@download/ENCFF002DGF.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF002DGD/@@download/ENCFF002DGD.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF002DGB/@@download/ENCFF002DGB.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF002DGG/@@download/ENCFF002DGG.fastq.gz" },
	"RBFOX2" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF002DGZ/@@download/ENCFF002DGZ.fastq.gz",
		"1nM" : "https://www.encodeproject.org/files/ENCFF002DHD/@@download/ENCFF002DHD.fastq.gz",
		"4nM" : "https://www.encodeproject.org/files/ENCFF002DHH/@@download/ENCFF002DHH.fastq.gz",
		"14nM" : "https://www.encodeproject.org/files/ENCFF002DHC/@@download/ENCFF002DHC.fastq.gz",
		"40nM" : "https://www.encodeproject.org/files/ENCFF002DHG/@@download/ENCFF002DHG.fastq.gz",
		"121nM" : "https://www.encodeproject.org/files/ENCFF002DHB/@@download/ENCFF002DHB.fastq.gz",
		"365nM" : "https://www.encodeproject.org/files/ENCFF002DHF/@@download/ENCFF002DHF.fastq.gz",
		"1100nM" : "https://www.encodeproject.org/files/ENCFF002DHA/@@download/ENCFF002DHA.fastq.gz",
		"3300nM" : "https://www.encodeproject.org/files/ENCFF002DHE/@@download/ENCFF002DHE.fastq.gz",
		"9800nM" : "https://www.encodeproject.org/files/ENCFF002DHI/@@download/ENCFF002DHI.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF002DHJ/@@download/ENCFF002DHJ.fastq.gz" },
	"MBNL1" : {
		"0nM" : "https://www.encodeproject.org/files/ENCFF002DGO/@@download/ENCFF002DGO.fastq.gz",
		"1nM" : "https://www.encodeproject.org/files/ENCFF002DGS/@@download/ENCFF002DGS.fastq.gz",
		"4nM" : "https://www.encodeproject.org/files/ENCFF002DGW/@@download/ENCFF002DGW.fastq.gz",
		"13nM" : "https://www.encodeproject.org/files/ENCFF002DGR/@@download/ENCFF002DGR.fastq.gz",
		"40nM" : "https://www.encodeproject.org/files/ENCFF002DGV/@@download/ENCFF002DGV.fastq.gz",
		"121nM" : "https://www.encodeproject.org/files/ENCFF002DGQ/@@download/ENCFF002DGQ.fastq.gz",
		"365nM" : "https://www.encodeproject.org/files/ENCFF002DGU/@@download/ENCFF002DGU.fastq.gz",
		"1090nM" : "https://www.encodeproject.org/files/ENCFF002DGP/@@download/ENCFF002DGP.fastq.gz",
		"3280nM" : "https://www.encodeproject.org/files/ENCFF002DGT/@@download/ENCFF002DGT.fastq.gz",
		"9800nM" : "https://www.encodeproject.org/files/ENCFF002DGX/@@download/ENCFF002DGX.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF002DGY/@@download/ENCFF002DGY.fastq.gz" },
	"AKAP8L" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF034RJL/@@download/ENCFF034RJL.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF211BFR/@@download/ENCFF211BFR.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF048KBT/@@download/ENCFF048KBT.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF051BKB/@@download/ENCFF051BKB.fastq.gz" },
	"APOBEC3C" : {
		"20nM" : "https://www.encodeproject.org/files/ENCFF596THB/@@download/ENCFF596THB.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF288DDJ/@@download/ENCFF288DDJ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF336ZLG/@@download/ENCFF336ZLG.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF051BKB/@@download/ENCFF051BKB.fastq.gz" },
	"CSDE1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF645OQW/@@download/ENCFF645OQW.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF485AIN/@@download/ENCFF485AIN.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF094VAN/@@download/ENCFF094VAN.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF275QND/@@download/ENCFF275QND.fastq.gz" },
	"EIF3D" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF609BEU/@@download/ENCFF609BEU.fastq.gz",
		"20nM" : "https://www.encodeproject.org/files/ENCFF901UAU/@@download/ENCFF901UAU.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF313IWB/@@download/ENCFF313IWB.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF940HMN/@@download/ENCFF940HMN.fastq.gz" },
	"EIF4H" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF458RCH/@@download/ENCFF458RCH.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF609ORZ/@@download/ENCFF609ORZ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF114BBL/@@download/ENCFF114BBL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF275QND/@@download/ENCFF275QND.fastq.gz" },
	"EXOSC4" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF515KZG/@@download/ENCFF515KZG.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF543ECU/@@download/ENCFF543ECU.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF547QPF/@@download/ENCFF547QPF.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF352XTP/@@download/ENCFF352XTP.fastq.gz" },
	"HNRNPA1L2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF324SNP/@@download/ENCFF324SNP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF200VIJ/@@download/ENCFF200VIJ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF313MLM/@@download/ENCFF313MLM.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF794LYE/@@download/ENCFF794LYE.fastq.gz" },
	"IGF2BP3" : {
		"20nM" : "https://www.encodeproject.org/files/ENCFF560UQP/@@download/ENCFF560UQP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF935OTT/@@download/ENCFF935OTT.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF066XQG/@@download/ENCFF066XQG.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF175MMH/@@download/ENCFF175MMH.fastq.gz" },
	"LIN28B" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF409TMI/@@download/ENCFF409TMI.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF708BUH/@@download/ENCFF708BUH.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF009HWR/@@download/ENCFF009HWR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF882HWV/@@download/ENCFF882HWV.fastq.gz" },
	"NSUN2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF106PAT/@@download/ENCFF106PAT.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF436MVF/@@download/ENCFF436MVF.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF399SZJ/@@download/ENCFF399SZJ.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF934REI/@@download/ENCFF934REI.fastq.gz" },
	"PABPC3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF225UDG/@@download/ENCFF225UDG.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF033GJN/@@download/ENCFF033GJN.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF836ATV/@@download/ENCFF836ATV.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF677VPY/@@download/ENCFF677VPY.fastq.gz" },
	"PPP1R10" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF943XFG/@@download/ENCFF943XFG.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF005JOX/@@download/ENCFF005JOX.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF514BCR/@@download/ENCFF514BCR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF647VIQ/@@download/ENCFF647VIQ.fastq.gz" },
	"PTBP1" : {
		"5nM" : "REVOKED",
		"20nM" : "REVOKED",
		"80nM" : "REVOKED",
		"320nM" : "REVOKED",
		"1300nM" : "REVOKED",
		"3900nM" : "REVOKED" },
	"RALY" : {
		"RALY" : "REVOKED" },
	"RBM11" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF767VHJ/@@download/ENCFF767VHJ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF604IEH/@@download/ENCFF604IEH.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF999PNF/@@download/ENCFF999PNF.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF101NND/@@download/ENCFF101NND.fastq.gz" },
	"RBM20" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF520OQE/@@download/ENCFF520OQE.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF653WQY/@@download/ENCFF653WQY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF781JHV/@@download/ENCFF781JHV.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF084WMM/@@download/ENCFF084WMM.fastq.gz" },
	"RBM3" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF576KOI/@@download/ENCFF576KOI.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF809IFX/@@download/ENCFF809IFX.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF745PBS/@@download/ENCFF745PBS.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF864GIN/@@download/ENCFF864GIN.fastq.gz" },
	"RBM5" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF444DXH/@@download/ENCFF444DXH.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF361NTW/@@download/ENCFF361NTW.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF150UEU/@@download/ENCFF150UEU.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF773UWT/@@download/ENCFF773UWT.fastq.gz" },
	"SAFB2" : {
		"80nM" : "https://www.encodeproject.org/files/ENCFF863XPB/@@download/ENCFF863XPB.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF632PPX/@@download/ENCFF632PPX.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF316BWJ/@@download/ENCFF316BWJ.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF056CJU/@@download/ENCFF056CJU.fastq.gz" },
	"SF3B6" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF228BDE/@@download/ENCFF228BDE.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF448IKY/@@download/ENCFF448IKY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF578APX/@@download/ENCFF578APX.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF084WMM/@@download/ENCFF084WMM.fastq.gz" },
	"SNRPB2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF960CSP/@@download/ENCFF960CSP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF078XHY/@@download/ENCFF078XHY.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF749DSK/@@download/ENCFF749DSK.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF418ZOY/@@download/ENCFF418ZOY.fastq.gz" },
	"SUCLG1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF746FBG/@@download/ENCFF746FBG.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF516HHS/@@download/ENCFF516HHS.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF764GUH/@@download/ENCFF764GUH.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF733GGQ/@@download/ENCFF733GGQ.fastq.gz" },
	"SYNCRIP" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF987JUM/@@download/ENCFF987JUM.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF031ZQZ/@@download/ENCFF031ZQZ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF311VEA/@@download/ENCFF311VEA.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF066UKZ/@@download/ENCFF066UKZ.fastq.gz" },
	"TDRD10" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF117GBU/@@download/ENCFF117GBU.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF637GMS/@@download/ENCFF637GMS.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF311QTO/@@download/ENCFF311QTO.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF773UWT/@@download/ENCFF773UWT.fastq.gz" },
	"THUMPD1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF223DCK/@@download/ENCFF223DCK.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF229VDA/@@download/ENCFF229VDA.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF102LTO/@@download/ENCFF102LTO.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF070BRT/@@download/ENCFF070BRT.fastq.gz" },
	"TRA2B" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF053XRQ/@@download/ENCFF053XRQ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF306CPI/@@download/ENCFF306CPI.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF777VGS/@@download/ENCFF777VGS.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF601ZQE/@@download/ENCFF601ZQE.fastq.gz" },
	"TROVE2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF245ISP/@@download/ENCFF245ISP.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF702NXM/@@download/ENCFF702NXM.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF779BQS/@@download/ENCFF779BQS.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF733GGQ/@@download/ENCFF733GGQ.fastq.gz" },
	"XRCC6" : {
		"20nM" : "https://www.encodeproject.org/files/ENCFF932TTA/@@download/ENCFF932TTA.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF885DNO/@@download/ENCFF885DNO.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF223OKF/@@download/ENCFF223OKF.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF940HMN/@@download/ENCFF940HMN.fastq.gz" },
	"XRN2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF814DJB/@@download/ENCFF814DJB.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF260BWV/@@download/ENCFF260BWV.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF122OCC/@@download/ENCFF122OCC.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF733MPN/@@download/ENCFF733MPN.fastq.gz" },
	"YBX2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF414JCF/@@download/ENCFF414JCF.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF182TEF/@@download/ENCFF182TEF.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF995XRI/@@download/ENCFF995XRI.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF881JYO/@@download/ENCFF881JYO.fastq.gz" },
	"ZC3H10" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF244KWF/@@download/ENCFF244KWF.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF951DBV/@@download/ENCFF951DBV.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF320AIR/@@download/ENCFF320AIR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF934REI/@@download/ENCFF934REI.fastq.gz" },
	"ZC3H18" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF905HAO/@@download/ENCFF905HAO.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF304PSD/@@download/ENCFF304PSD.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF948RDB/@@download/ENCFF948RDB.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF647VIQ/@@download/ENCFF647VIQ.fastq.gz" },
	"ZFP36L1" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF573PAZ/@@download/ENCFF573PAZ.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF676GIJ/@@download/ENCFF676GIJ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF838TGG/@@download/ENCFF838TGG.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF084WMM/@@download/ENCFF084WMM.fastq.gz" },
	"ZFP36L2" : {
		"5nM" : "https://www.encodeproject.org/files/ENCFF726RAA/@@download/ENCFF726RAA.fastq.gz",
		"80nM" : "https://www.encodeproject.org/files/ENCFF712YGA/@@download/ENCFF712YGA.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF818NQL/@@download/ENCFF818NQL.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF084WMM/@@download/ENCFF084WMM.fastq.gz" },
	"ZRANB2" : {
		"80nM" : "https://www.encodeproject.org/files/ENCFF158XJZ/@@download/ENCFF158XJZ.fastq.gz",
		"320nM" : "https://www.encodeproject.org/files/ENCFF090FQJ/@@download/ENCFF090FQJ.fastq.gz",
		"1300nM" : "https://www.encodeproject.org/files/ENCFF488DBR/@@download/ENCFF488DBR.fastq.gz",
		"input" : "https://www.encodeproject.org/files/ENCFF056CJU/@@download/ENCFF056CJU.fastq.gz" }
}
